apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  labels:
    app: loki-svc-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loki-svc-node
  template:
    metadata:
      labels:
        app: loki-svc-node
    spec:
      containers:
      - name: loki-svc-node
        image: jaaff/loki-svc-kubernetes
        ports:
          - protocol: TCP
            port: 22022
            targetPort: 22022
          - protocol: TCP
            port: 22023
            targetPort: 22023
          - protocol: UDP
            port: 1090
            targetPort: 1090
          